### ISSUE TITLE
edit the build.yml

### ISSUE THREAD

**Issue by briansbrian** [SegiMan/Yamb#1]
i think this is your issue, maybe android sdk, this is how to fix it in build.yaml

- name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: echo y | buildozer android debug
          buildozer_version: master

echo y into the buildozer command to accept android sdk license

**Comment by briansbrian** [comment]
you are welcome to help with mine.......  https://github.com/briansbrian/tictactoe.git

**Comment by SegiMan** [comment]
> i think this is your issue, maybe android sdk, this is how to fix it in build.yaml
> 
> * name: Build with Buildozer
>   uses: ArtemSBulgakov/buildozer-action@v1
>   id: buildozer
>   with:
>   command: echo y | buildozer android debug
>   buildozer_version: master
> 
> echo y into the buildozer command to accept android sdk license

Thank you for the suggestion. Unfortunatelly, it didn't solve the issue. I'd also be glad to try help with your code, but I just started working with kiwi and this is my first project with it. I have next to zero knowledge of android apk-s, or what I'm doing really, so I'm afraid I can't be of much help. I thought it will be a simple matter to make an apk out of an app which is already working on pc as long as I follow the instructions, but I don't understand how any of the build is actually done.

**Comment by briansbrian** [comment]
Actually, we are kinda the same. Am also figuring out his stuff and trying to help where i can.

**Comment by Novfensec** [comment]
# Problems Solved

Use the workflow below.
It fully automates the build process accepting the licenses vanishing all errors during the apk build.

Sample repo at https://github.com/Novfensec/SAMPLE-KIVYMD-APP

```yaml
# Sample repository at https://github.com/Novfensec/SAMPLE-KIVYMD-APP

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libunwind-dev \
            zlib1g-dev
          sudo apt-get install -y \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            zlib1g-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            uuid-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
          sudo apt-get install -y \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            automake

      # Set up Java 17 required by Gradle
      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or 'zulu', 'liberica', etc.
          java-version: '17'

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' #set your python version

      # Install pip dependencies
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # Build with Buildozer
      - name: Build with Buildozer
        id: buildozer
        run: |
          yes | buildozer -v android debug
        # yes | buildozer -v android release
        # run this for generating aab (Android App Bundle) [Required by google play]

      # Upload artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/*.apk
            bin/*.aab
```
